### ISSUE TITLE
Single global config file for all users causes problems

### ISSUE THREAD

**Issue by jjv5** [fmi-basel/GUIFold#1]
We would like to distribute this software (sbgrid.org).
The single global config file that lives under GUIfold directory means only a sysadmin would be able to change things.

Requirement for other things like cluster templates and the colabfold databases to live under the GUIfold directory also present problems for multisite/multiuser use.

Is there a way all of these things can be configured by an end user who does not have write permission to the main GUIfold directory? This is how the software would be installed on a cluster.

**Comment by georgkempf** [comment]
I added the option to define a custom path to a cluster template and to load a predefined configuration file from any location. Both can be done in the Settings dialog of the GUI. The databases can be stored in any location and the path can be set in the configuration file or Settings dialog.
